packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  puppeteer: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - vite@8.3.2
