import { PrismaClient } from '@lms/database';
import type { DateRange } from './financial.queries';

function rangeWhere(range: DateRange) {
  if (!range.from && !range.to) return undefined;
  return {
    ...(range.from ? { gte: range.from } : {}),
    ...(range.to ? { lte: range.to } : {}),
  };
}

/** Share generated by invoices created within the range — "how much share
 * did we owe doctors based on billing in this period". */
export async function getTotalSharePayable(
  prisma: PrismaClient,
  tenantId: string,
  range: DateRange,
) {
  const result = await prisma.doctorShare.aggregate({
    where: { tenantId, createdAt: rangeWhere(range) },
    _sum: { calculatedAmount: true },
  });
  return Number(result._sum.calculatedAmount ?? 0);
}

/** Share actually paid out to doctors within the range. */
export async function getTotalSharePaid(
  prisma: PrismaClient,
  tenantId: string,
  range: DateRange,
) {
  const result = await prisma.doctorShare.aggregate({
    where: { tenantId, paidAt: { not: null, ...(rangeWhere(range) ?? {}) } },
    _sum: { paidAmount: true },
  });
  return Number(result._sum.paidAmount ?? 0);
}

/** Total unpaid share owed right now, across all doctors — a snapshot like
 * Outstanding in financial.queries.ts, not date-ranged (money owed doesn't
 * belong to a single period just because it was earned in one). */
export async function getPendingShare(prisma: PrismaClient, tenantId: string) {
  const shares = await prisma.doctorShare.findMany({
    where: { tenantId },
    select: { calculatedAmount: true, paidAmount: true },
  });
  return shares.reduce(
    (sum, s) => sum + (Number(s.calculatedAmount) - Number(s.paidAmount ?? 0)),
    0,
  );
}

export interface TopDoctorRow {
  doctorId: string;
  doctorName: string;
  patientsReferred: number;
  revenueGenerated: number;
  totalShare: number;
}

/** Top referring doctors by share generated in range — same shape of
 * aggregation the per-doctor Doctor Dashboard already does, just grouped
 * across all doctors instead of scoped to one. */
export async function getTopReferringDoctors(
  prisma: PrismaClient,
  tenantId: string,
  range: DateRange,
  limit = 10,
): Promise<TopDoctorRow[]> {
  const shares = await prisma.doctorShare.findMany({
    where: { tenantId, createdAt: rangeWhere(range) },
    include: {
      doctor: { select: { id: true, fullName: true } },
      invoice: { select: { grandTotal: true, booking: { select: { patientId: true } } } },
    },
  });

  const byDoctor = new Map<
    string,
    { doctorName: string; patientIds: Set<string>; revenue: number; share: number }
  >();

  for (const s of shares) {
    const key = s.doctorId;
    const entry = byDoctor.get(key) ?? {
      doctorName: s.doctor.fullName,
      patientIds: new Set<string>(),
      revenue: 0,
      share: 0,
    };
    if (s.invoice.booking?.patientId) entry.patientIds.add(s.invoice.booking.patientId);
    entry.revenue += Number(s.invoice.grandTotal);
    entry.share += Number(s.calculatedAmount);
    byDoctor.set(key, entry);
  }

  return Array.from(byDoctor.entries())
    .map(([doctorId, v]) => ({
      doctorId,
      doctorName: v.doctorName,
      patientsReferred: v.patientIds.size,
      revenueGenerated: v.revenue,
      totalShare: v.share,
    }))
    .sort((a, b) => b.totalShare - a.totalShare)
    .slice(0, limit);
}

export interface ShareTrendPoint {
  date: string; // yyyy-mm-dd
  totalShare: number;
}

/**
 * Daily-bucketed share trend within range — the frontend line chart can
 * roll this up into weeks/months itself; bucketing here in JS (not raw
 * SQL) to stay consistent with how every other query in this codebase is
 * written, and because per-lab data volumes are small enough that this is
 * not a performance concern (see docs/05_Analytics_Architecture.md §3.3).
 */
export async function getDoctorShareTrend(
  prisma: PrismaClient,
  tenantId: string,
  range: DateRange,
): Promise<ShareTrendPoint[]> {
  const shares = await prisma.doctorShare.findMany({
    where: { tenantId, createdAt: rangeWhere(range) },
    select: { createdAt: true, calculatedAmount: true },
    orderBy: { createdAt: 'asc' },
  });

  const byDay = new Map<string, number>();
  for (const s of shares) {
    const day = s.createdAt.toISOString().slice(0, 10);
    byDay.set(day, (byDay.get(day) ?? 0) + Number(s.calculatedAmount));
  }

  return Array.from(byDay.entries())
    .map(([date, totalShare]) => ({ date, totalShare }))
    .sort((a, b) => a.date.localeCompare(b.date));
}

export async function getDoctorShareOverview(
  prisma: PrismaClient,
  tenantId: string,
  range: DateRange,
) {
  const [totalSharePayable, totalSharePaid, pendingShare, topReferringDoctors, shareTrend] =
    await Promise.all([
      getTotalSharePayable(prisma, tenantId, range),
      getTotalSharePaid(prisma, tenantId, range),
      getPendingShare(prisma, tenantId),
      getTopReferringDoctors(prisma, tenantId, range),
      getDoctorShareTrend(prisma, tenantId, range),
    ]);

  return {
    totalSharePayable,
    totalSharePaid,
    pendingShare,
    topReferringDoctors,
    shareTrend,
  };
}
